import { Metadata } from "next";

interface MetadataProps {
    title?: string;
    description?: string;
    icons?: Metadata["icons"];
    noIndex?: boolean;
    keywords?: string[];
    author?: string;
    twitterHandle?: string;
    type?: "website" | "article" | "profile";
    locale?: string;
    alternates?: Record<string, string>;
    publishedTime?: string;
    modifiedTime?: string;
}

export const generateMetadata = ({
    title = `7Gence`,
    description = `7Gence is an AI Agency which leverage AI to automate workflows,build AI powered custom Agents, and boost productivity.`,
    icons = [
        {
            rel: "icon",
            url: "/icons/favicon.png",
            type: "image/png",
            sizes: "32x32 48x48 64x64 96x96 128x128 256x256",
        },
        {
            rel: "apple-touch-icon",
            url: "/icons/favicon.png",
            sizes: "180x180",
            type: "image/png",
        },
    ],
    noIndex = false,
    keywords = [
        "7Gence",
        "7gence",
        "seven",
        "7",
        "11",
        "AI",
        "AI Agency",
        "Customer care",
        "AI Customer care",
        "AI Voice agent",
        "Eleven labs",
        "SEO optimization",
        "influencer marketing",
        "email marketing automation",
        "chatbot integration",
        "customer segmentation",
        "market research",
        "brand management",
        "video marketing",
        "mobile marketing",
        "voice search optimization",
        "personalization strategies",
        "behavioral targeting",
        "customer relationship management",
        "data-driven marketing",
        "programmatic advertising",
        "content strategy",
        "UX design",
        "engagement optimization",
        "conversion funnel optimization",
        "landing page optimization",
        "customer experience",
        "interactive content",
        "augmented reality marketing",
        "virtual reality campaigns",
        "marketing storytelling",
        "account-based marketing",
        "retargeting campaigns",
        "cross-channel marketing",
        "omnichannel strategy",
        "CRM integration",
        "marketing automation platforms",
        "predictive analytics",
        "lead nurturing",
        "mobile app marketing",
        "inbound marketing",
        "outbound marketing",
        "PPC campaign optimization",
        "ad retargeting",
        "programmatic buying",
        "social listening",
        "brand sentiment analysis",
        "A/B testing",
        "growth hacking",
        "customer lifecycle marketing",
        "marketing personalization",
        "customer feedback analysis",
        "viral marketing",
        "user-generated content",
        "influencer collaborations",
        "conversion rate optimization",
        "digital ad tracking",
        "e-commerce marketing",
        "SEO content optimization",
        "web analytics",
        "behavioral analytics",
        "in-app advertising",
        "marketing attribution",
        "data visualization",
        "campaign performance reporting",
        "customer journey mapping",
        "heatmapping analysis",
        "marketing segmentation",
        "brand positioning",
        "niche marketing",
        "event marketing",
        "sponsorship marketing",
        "loyalty programs",
        "affiliate marketing",
        "display advertising",
        "native advertising",
        "digital PR",
        "content curation",
        "search engine marketing",
        "local SEO",
        "global SEO",
        "competitive analysis",
        "keyword research",
        "dynamic creative optimization",
        "ad creative testing",
        "marketing attribution models",
        "omnichannel analytics",
        "customer data platforms",
        "big data marketing",
        "machine learning insights",
        "predictive customer modeling",
        "AI-powered recommendations",
        "chatbot marketing",
        "smart content delivery",
        "interactive advertising",
        "real-time bidding",
        "supply-side platforms",
        "demand-side platforms",
        "programmatic media",
        "digital storytelling",
        "search marketing",
        "conversion optimization techniques",
        "data mining for marketing",
        "sales funnel automation",
        "multivariate testing",
        "AI-powered analytics"
      ]
      ,
    author = process.env.NEXT_PUBLIC_AUTHOR_NAME,
    type = "website",
}: MetadataProps = {}): Metadata => {
    const metadataBase = new URL(process.env.NEXT_PUBLIC_APP_URL || "https://7gence.com");

    return {
        metadataBase,
        title: {
            template: `%s | ${process.env.NEXT_PUBLIC_APP_NAME}`,
            default: title
        },
        description,
        keywords,
        authors: [{ name: author }],
        creator: author,
        publisher: process.env.NEXT_PUBLIC_APP_NAME,
        formatDetection: {
            email: false,
            address: false,
            telephone: false,
        },
        icons,
    };
};